#lang racket
(provide (all-defined-out))
(require 2htdp/image)
(define my-brown (color 91 46 0))
(define board (bitmap "m-images/mancala.jpg"))
(define main-frame-background (bitmap "m-images/mancala_welcome-background.png"))
(define mancala-game-background (bitmap "m-images/game-background.png"))
(define background (bitmap "m-images/dark-concrete-wall-hd-wallpapers-on-picsfair-com.jpg"))
(define 1-player-rest (bitmap "m-images/1-player-rest.png"))
(define 1-player-hover (bitmap "m-images/1-player-hover.png"))
(define 1-player-down (bitmap "m-images/1-player-down.png"))
(define 2-player-rest (bitmap "m-images/2-player-rest.png"))
(define 2-player-hover (bitmap "m-images/2-player-hover.png"))
(define 2-player-down (bitmap "m-images/2-player-down.png"))
(define how-to-play-rest (bitmap "m-images/how-to-play-rest.png"))
(define how-to-play-hover (bitmap "m-images/how-to-play-hover.png"))
(define how-to-play-down (bitmap "m-images/how-to-play-down.png"))
(define settings-rest (bitmap "m-images/settings-rest.png"))
(define settings-hover (bitmap "m-images/settings-hover.png"))
(define settings-down (bitmap "m-images/settings-down.png"))
(define back-rest (bitmap "m-images/back-rest.png"))
(define back-hover (bitmap "m-images/back-hover.png"))
(define back-down (bitmap "m-images/back-down.png"))
(define how-to-play-1 (bitmap "m-images/how-to-play-mancala-1.jpg"))
(define how-to-play-2 (bitmap "m-images/how-to-play-mancala-2.jpg"))
(define instruction-back-rest (bitmap "m-images/instruction-back-rest.png"))
(define instruction-back-hover (bitmap "m-images/instruction-back-hover.png"))
(define instruction-back-down (bitmap "m-images/instruction-back-down.png"))
(define settings-frame-background (bitmap "m-images/settings-background.png"))
(define checkbox (bitmap "m-images/checkbox.png"))
(define checkbox-hover (bitmap "m-images/checkbox-hover.png"))
(define checkbox-down (bitmap "m-images/checkbox-down.png"))
(define variant1-rest (bitmap "m-images/variant1-rest.png"))
(define variant1-hover (bitmap "m-images/variant1-hover.png"))
(define variant1-down (bitmap "m-images/variant1-down.png"))
(define variant2-rest (bitmap "m-images/variant2-rest.png"))
(define variant2-hover (bitmap "m-images/variant2-hover.png"))
(define variant2-down (bitmap "m-images/variant2-down.png"))
(define mancala-back-rest (bitmap "m-images/mancala-back-rest.png"))
(define mancala-back-hover (bitmap "m-images/mancala-back-hover.png"))
(define mancala-back-down (bitmap "m-images/mancala-back-down.png"))
(define restart-rest (bitmap "m-images/restart-rest.png"))
(define restart-hover (bitmap "m-images/restart-hover.png"))
(define restart-down (bitmap "m-images/restart-press.png"))
(define quit-rest (bitmap "m-images/quit-rest.png"))
(define quit-hover (bitmap "m-images/quit-hover.png"))
(define quit-down (bitmap "m-images/quit-press.png"))
(define game-over-background (bitmap "m-images/game-over-background.png"))


(define (normal_cups i)
  (overlay (text (~a i) 32 "white")
           (underlay/xy (underlay/xy (circle 31 'solid my-brown) 0 31 (rectangle 62 70 'solid my-brown))
                        0 70 (circle 31 'solid my-brown))))
(define (normal_cups_big i)
  (overlay (text (~a i) 38 "white")
           (underlay/xy (underlay/xy (circle 31 'solid my-brown) 0 31 (rectangle 62 70 'solid my-brown))
                        0 70 (circle 31 'solid my-brown))))

(define (mancala_cups i)
  (overlay (text (~a i) 32 "white")
           (underlay/xy (underlay/xy (circle 31 'solid my-brown) 0 31 (rectangle 62 250 'solid my-brown))
                        0 250 (circle 31 'solid my-brown))))
(define (mancala_cups_big i)
  (overlay (text (~a i) 38 "white")
           (underlay/xy (underlay/xy (circle 31 'solid my-brown) 0 31 (rectangle 62 250 'solid my-brown))
                        0 250 (circle 31 'solid my-brown))))
