#lang racket
(require 2htdp/image)

(provide (all-defined-out))

(define vacant (bitmap "images/null.png"))

(define background (bitmap "images/background.png"))

(define congratulations (bitmap "images/Congratulations.png"))

(define gameover (bitmap "images/Gameover.png"))

(define wordsearch (bitmap "images/Wordsearch.png"))

(define welcome-background (bitmap "images/welcome-background.png"))

(define a_press (bitmap "images/A_press.png"))
(define b_press (bitmap "images/B_press.png"))
(define c_press (bitmap "images/C_press.png"))
(define d_press (bitmap "images/D_press.png"))
(define e_press (bitmap "images/E_press.png"))
(define f_press (bitmap "images/F_press.png"))
(define g_press (bitmap "images/G_press.png"))
(define h_press (bitmap "images/H_press.png"))
(define i_press (bitmap "images/I_press.png"))
(define j_press (bitmap "images/J_press.png"))
(define k_press (bitmap "images/K_press.png"))
(define l_press (bitmap "images/L_press.png"))
(define m_press (bitmap "images/M_press.png"))
(define n_press (bitmap "images/N_press.png"))
(define o_press (bitmap "images/O_press.png"))
(define p_press (bitmap "images/P_press.png"))
(define q_press (bitmap "images/Q_press.png"))
(define r_press (bitmap "images/R_press.png"))
(define s_press (bitmap "images/S_press.png"))
(define t_press (bitmap "images/T_press.png"))
(define u_press (bitmap "images/U_press.png"))
(define v_press (bitmap "images/V_press.png"))
(define w_press (bitmap "images/W_press.png"))
(define x_press (bitmap "images/X_press.png"))
(define y_press (bitmap "images/Y_press.png"))
(define z_press (bitmap "images/Z_press.png"))
(define retry_press (bitmap "images/RETRY_press.png"))
(define next_press (bitmap "images/NEXT_press.png"))
(define quit_press (bitmap "images/QUIT_press.png"))
(define play-levels_press (bitmap "images/Play_levels_press.png"))
(define create-level_press (bitmap "images/Create-level_press.png"))

(define a_normal (bitmap "images/A_normal.png"))
(define b_normal (bitmap "images/B_normal.png"))
(define c_normal (bitmap "images/C_normal.png"))
(define d_normal (bitmap "images/D_normal.png"))
(define e_normal (bitmap "images/E_normal.png"))
(define f_normal (bitmap "images/F_normal.png"))
(define g_normal (bitmap "images/G_normal.png"))
(define h_normal (bitmap "images/H_normal.png"))
(define i_normal (bitmap "images/I_normal.png"))
(define j_normal (bitmap "images/J_normal.png"))
(define k_normal (bitmap "images/K_normal.png"))
(define l_normal (bitmap "images/L_normal.png"))
(define m_normal (bitmap "images/M_normal.png"))
(define n_normal (bitmap "images/N_normal.png"))
(define o_normal (bitmap "images/O_normal.png"))
(define p_normal (bitmap "images/P_normal.png"))
(define q_normal (bitmap "images/Q_normal.png"))
(define r_normal (bitmap "images/R_normal.png"))
(define s_normal (bitmap "images/S_normal.png"))
(define t_normal (bitmap "images/T_normal.png"))
(define u_normal (bitmap "images/U_normal.png"))
(define v_normal (bitmap "images/V_normal.png"))
(define w_normal (bitmap "images/W_normal.png"))
(define x_normal (bitmap "images/X_normal.png"))
(define y_normal (bitmap "images/Y_normal.png"))
(define z_normal (bitmap "images/Z_normal.png"))
(define retry_normal (bitmap "images/RETRY_normal.png"))
(define next_normal (bitmap "images/NEXT_normal.png"))
(define quit_normal (bitmap "images/QUIT_normal.png"))
(define play-levels_normal (bitmap "images/Play_levels_normal.png"))
(define create-level_normal (bitmap "images/Create-level_normal.png"))

(define a_hover (bitmap "images/A_hover.png"))
(define b_hover (bitmap "images/B_hover.png"))
(define c_hover (bitmap "images/C_hover.png"))
(define d_hover (bitmap "images/D_hover.png"))
(define e_hover (bitmap "images/E_hover.png"))
(define f_hover (bitmap "images/F_hover.png"))
(define g_hover (bitmap "images/G_hover.png"))
(define h_hover (bitmap "images/H_hover.png"))
(define i_hover (bitmap "images/I_hover.png"))
(define j_hover (bitmap "images/J_hover.png"))
(define k_hover (bitmap "images/K_hover.png"))
(define l_hover (bitmap "images/L_hover.png"))
(define m_hover (bitmap "images/M_hover.png"))
(define n_hover (bitmap "images/N_hover.png"))
(define o_hover (bitmap "images/O_hover.png"))
(define p_hover (bitmap "images/P_hover.png"))
(define q_hover (bitmap "images/Q_hover.png"))
(define r_hover (bitmap "images/R_hover.png"))
(define s_hover (bitmap "images/S_hover.png"))
(define t_hover (bitmap "images/T_hover.png"))
(define u_hover (bitmap "images/U_hover.png"))
(define v_hover (bitmap "images/V_hover.png"))
(define w_hover (bitmap "images/W_hover.png"))
(define x_hover (bitmap "images/X_hover.png"))
(define y_hover (bitmap "images/Y_hover.png"))
(define z_hover (bitmap "images/Z_hover.png"))
(define retry_hover (bitmap "images/RETRY_hover.png"))
(define next_hover (bitmap "images/NEXT_hover.png"))
(define quit_hover (bitmap "images/QUIT_hover.png"))
(define play-levels_hover (bitmap "images/Play_levels_hover.png"))
(define create-level_hover (bitmap "images/Create-level_hover.png"))

(define back_press (bitmap "images/Back_press.png"))
(define back_hover (bitmap "images/Back_hover.png"))
(define back_normal (bitmap "images/Back_normal.png"))

(define play_press (bitmap "images/Play_press.png"))
(define play_hover (bitmap "images/Play_hover.png"))
(define play_normal (bitmap "images/Play_normal.png"))

(define timer (bitmap "images/Timer.png"))
(define word-box (bitmap "images/word-box.png"))
(define solution (bitmap "images/Solution.png"))